export enum FETCH_CONFIG {
    REQUEST = 'FETCH_CONFIG_REQUEST',
    SUCCESS = 'FETCH_CONFIG_SUCCESS',
    FAILURE = 'FETCH_CONFIG_FAILURE',
    CLOSE_ERROR_MODAL_REQUEST = 'FETCH_CONFIG_CLOSE_ERROR_MODAL_REQUEST',
}
